package output

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/critbot/claude-review/internal/agents"
	"github.com/critbot/claude-review/internal/diff"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// WriteMarkdown generates a REVIEW.md file and writes it to path.
func WriteMarkdown(path string, result *agents.PipelineResult, payload *diff.Payload) error {
	content := buildMarkdown(result, payload)
	return os.WriteFile(path, []byte(content), 0644)
}

func buildMarkdown(result *agents.PipelineResult, payload *diff.Payload) string {
	var b strings.Builder

	// Header
	b.WriteString("# Code Review Report\n\n")
	b.WriteString(fmt.Sprintf("Generated by [claude-review](https://github.com/critbot/claude-review) on %s\n\n",
		time.Now().Format("2006-01-02 15:04 MST")))

	if payload.PRTitle != "" {
		b.WriteString(fmt.Sprintf("**PR**: %s\n", payload.PRTitle))
	}
	if payload.BaseRef != "" && payload.HeadRef != "" {
		b.WriteString(fmt.Sprintf("**Branch**: `%s` → `%s`\n", payload.HeadRef, payload.BaseRef))
	}
	b.WriteString(fmt.Sprintf("**Changes**: +%d -%d across %d files\n\n",
		payload.TotalAdditions, payload.TotalDeletions, len(payload.Files)))

	// Summary
	counts := result.SeverityCounts()
	b.WriteString("## Summary\n\n")
	b.WriteString(fmt.Sprintf("| Severity | Count |\n|----------|-------|\n"))
	b.WriteString(fmt.Sprintf("| 🔴 Critical | %d |\n", counts[agents.SeverityCritical]))
	b.WriteString(fmt.Sprintf("| 🟠 High | %d |\n", counts[agents.SeverityHigh]))
	b.WriteString(fmt.Sprintf("| 🟡 Medium | %d |\n", counts[agents.SeverityMedium]))
	b.WriteString(fmt.Sprintf("| 💡 Suggestion | %d |\n", counts[agents.SeveritySuggestion]))
	b.WriteString(fmt.Sprintf("| Filtered out | %d |\n\n", result.SkippedCount))

	b.WriteString(fmt.Sprintf("**Cost**: $%.4f · **Agents**: %d finder + verifier + ranker · **Time**: %.1fs\n\n",
		result.Usage.EstimatedCostUSD, len(result.Usage.ByAgent)-2, result.DurationSecs))

	if len(result.Findings) == 0 {
		b.WriteString("---\n\n✅ **No issues found.** This diff looks clean.\n")
		return b.String()
	}

	// Findings by severity
	for _, sev := range []agents.Severity{agents.SeverityCritical, agents.SeverityHigh, agents.SeverityMedium, agents.SeveritySuggestion} {
		findings := filterBySeverity(result.Findings, sev)
		if len(findings) == 0 {
			continue
		}

		emoji := sevEmoji(sev)
		b.WriteString(fmt.Sprintf("---\n\n## %s %s\n\n", emoji, cases.Title(language.English).String(string(sev))))

		for _, f := range findings {
			b.WriteString(fmt.Sprintf("### %s", f.Description[:min(len(f.Description), 80)]))
			if len(f.Description) > 80 {
				b.WriteString("...")
			}
			b.WriteString("\n\n")

			b.WriteString(fmt.Sprintf("**File**: `%s`", f.File))
			if f.Line > 0 {
				b.WriteString(fmt.Sprintf(" · **Line**: %d", f.Line))
				if f.EndLine > f.Line {
					b.WriteString(fmt.Sprintf("–%d", f.EndLine))
				}
			}
			b.WriteString(fmt.Sprintf(" · **Category**: %s · **Confidence**: %.0f%%\n\n", f.Category, f.Confidence*100))

			b.WriteString(f.Description + "\n\n")

			if f.CodeSnippet != "" {
				b.WriteString("```\n" + f.CodeSnippet + "\n```\n\n")
			}

			if f.SuggestedFix != "" {
				b.WriteString("**Suggested Fix**:\n\n")
				b.WriteString("```\n" + f.SuggestedFix + "\n```\n\n")
			}

			if f.NeedsContext {
				b.WriteString("> ⚠️ This finding may require broader codebase context not visible in the diff.\n\n")
			}
			if f.RankNote != "" {
				b.WriteString(fmt.Sprintf("> 📋 %s\n\n", f.RankNote))
			}

			b.WriteString("---\n\n")
		}
	}

	return b.String()
}

func filterBySeverity(findings []agents.Finding, sev agents.Severity) []agents.Finding {
	var result []agents.Finding
	for _, f := range findings {
		if f.Severity == sev {
			result = append(result, f)
		}
	}
	return result
}

func sevEmoji(s agents.Severity) string {
	switch s {
	case agents.SeverityCritical:
		return "🔴"
	case agents.SeverityHigh:
		return "🟠"
	case agents.SeverityMedium:
		return "🟡"
	default:
		return "💡"
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
